var VOCAB = [
  { title: "核心高頻字 1（常用動詞）", words: [
    "be|是|v.|I am a student.|我是一個學生。",
    "have|有|v.|I have a pen.|我有一支筆。",
    "do|做|v.|Do your homework.|做你的功課。",
    "go|去|v.|I go to school.|我去學校。",
    "get|得到|v.|I get a gift.|我得到一份禮物。",
    "make|製作|v.|I make a cake.|我製作蛋糕。",
    "take|拿；帶|v.|Take this book.|拿這本書。",
    "come|來|v.|Come here.|過來。",
    "see|看見|v.|I see a bird.|我看見一隻鳥。",
    "know|知道|v.|I know him.|我認識他。"
  ]},
  { title: "核心高頻字 2（常用動詞）", words: [
    "say|說|v.|Say your name.|說出你的名字。",
    "think|想；認為|v.|I think so.|我認為是這樣。",
    "want|想要|v.|I want water.|我想要水。",
    "need|需要|v.|I need help.|我需要幫助。",
    "like|喜歡|v.|I like music.|我喜歡音樂。",
    "love|愛|v.|I love my family.|我愛我的家人。",
    "feel|感覺|v.|I feel happy.|我感到開心。",
    "look|看|v.|Look at me.|看着我。",
    "use|使用|v.|Use a pen.|用一支筆。",
    "find|找到|v.|Find the key.|找到鎖匙。"
  ]},
  { title: "核心高頻字 3（常用動詞）", words: [
    "give|給|v.|Give me the book.|把書給我。",
    "put|放|v.|Put it down.|把它放下。",
    "tell|告訴|v.|Tell me a story.|告訴我一個故事。",
    "ask|問|v.|Ask a question.|問一個問題。",
    "work|工作|v.|I work every day.|我每天工作。",
    "play|玩|v.|Let's play.|我們一起玩吧。",
    "run|跑|v.|I run fast.|我跑得快。",
    "walk|走路|v.|I walk to school.|我走路去學校。",
    "eat|吃|v.|I eat rice.|我吃米飯。",
    "drink|喝|v.|Drink some water.|喝點水。"
  ]},
  { title: "核心高頻字 4（常用動詞）", words: [
    "sleep|睡覺|v.|I sleep early.|我很早睡。",
    "read|閱讀|v.|I read books.|我閱讀書本。",
    "write|寫|v.|Write your name.|寫你的名字。",
    "listen|聆聽|v.|Listen to me.|聽我說。",
    "watch|觀看|v.|I watch TV.|我看電視。",
    "buy|買|v.|I buy fruit.|我買水果。",
    "sell|賣|v.|They sell food.|他們賣食物。",
    "pay|付款|v.|I pay the money.|我付錢。",
    "help|幫助|v.|Help me, please.|請幫助我。",
    "open|打開|v.|Open the door.|打開門。"
  ]},
  { title: "核心高頻字 5（常用動詞）", words: [
    "close|關上|v.|Close the door.|關上門。",
    "start|開始|v.|Let's start.|我們開始吧。",
    "stop|停止|v.|Stop the car.|停車。",
    "finish|完成|v.|I finish my work.|我完成工作。",
    "wait|等待|v.|Wait for me.|等我。",
    "meet|見面|v.|Nice to meet you.|很高興認識你。",
    "call|打電話|v.|Call me later.|稍後打給我。",
    "talk|談話|v.|Let's talk.|我們談談。",
    "speak|說話|v.|I speak English.|我說英語。",
    "live|居住|v.|I live in Hong Kong.|我住在香港。"
  ]},
  { title: "核心高頻字 6（常用動詞）", words: [
    "wear|穿着|v.|I wear a jacket.|我穿着外套。",
    "carry|攜帶|v.|I carry a bag.|我拿着袋子。",
    "bring|帶來|v.|Bring your book.|帶你的書來。",
    "keep|保持|v.|Keep quiet.|保持安靜。",
    "hold|握着|v.|Hold my hand.|握我的手。",
    "send|寄；發送|v.|Send me an email.|寄電郵給我。",
    "show|展示|v.|Show me your work.|給我看你的功課。",
    "learn|學習|v.|I learn English.|我學英語。",
    "teach|教導|v.|She teaches maths.|她教數學。",
    "study|用功；研究|v.|I study hard.|我努力用功。"
  ]},
  { title: "核心高頻字 7（常用動詞）", words: [
    "understand|明白|v.|I understand you.|我明白你。",
    "remember|記得|v.|Remember this.|記住這個。",
    "forget|忘記|v.|Don't forget.|不要忘記。",
    "try|嘗試|v.|Try again.|再試一次。",
    "choose|選擇|v.|Choose one.|選一個。",
    "change|改變|v.|Change your clothes.|換衣服。",
    "move|移動|v.|Move the chair.|移動椅子。",
    "turn|轉|v.|Turn left.|轉左。",
    "return|回來；歸還|v.|Return the book.|歸還書本。",
    "leave|離開|v.|I leave at eight.|我八時離開。"
  ]},
  { title: "核心高頻字 8（常用動詞）", words: [
    "sit|坐|v.|Sit down.|坐下。",
    "stand|站|v.|Stand up.|站起來。",
    "win|贏|v.|We win the game.|我們贏了比賽。",
    "lose|輸；遺失|v.|Don't lose the key.|不要弄丟鎖匙。",
    "catch|捉住|v.|Catch the ball.|接住球。",
    "throw|投擲|v.|Throw the ball.|投球。",
    "break|打破|v.|Don't break it.|不要打破它。",
    "cut|切|v.|Cut the cake.|切蛋糕。",
    "grow|生長|v.|Plants grow.|植物生長。",
    "cook|煮|v.|I cook dinner.|我煮晚飯。"
  ]},
  { title: "核心高頻字 9（常用形容詞）", words: [
    "big|大的|adj.|A big dog.|一隻大狗。",
    "small|小的|adj.|A small cat.|一隻小貓。",
    "good|好的|adj.|Good job!|做得好！",
    "bad|壞的|adj.|Bad weather.|壞天氣。",
    "new|新的|adj.|A new book.|一本新書。",
    "old|舊的；老的|adj.|An old man.|一個老人。",
    "hot|熱的|adj.|Hot soup.|熱湯。",
    "cold|冷的|adj.|Cold water.|冷水。",
    "high|高的|adj.|A high wall.|一道高牆。",
    "low|低的|adj.|A low table.|一張矮桌。"
  ]},
  { title: "核心高頻字 10（常用形容詞）", words: [
    "long|長的|adj.|Long hair.|長頭髮。",
    "short|短的；矮的|adj.|Short hair.|短頭髮。",
    "fast|快的|adj.|A fast car.|一輛快車。",
    "slow|慢的|adj.|A slow train.|一列慢火車。",
    "easy|容易的|adj.|An easy question.|容易的問題。",
    "difficult|困難的|adj.|A difficult test.|困難的測驗。",
    "happy|開心的|adj.|I am happy.|我很開心。",
    "sad|傷心的|adj.|She is sad.|她很傷心。",
    "clean|乾淨的|adj.|Clean hands.|乾淨的手。",
    "dirty|骯髒的|adj.|Dirty shoes.|骯髒的鞋。"
  ]},
  { title: "核心高頻字 11（常用形容詞）", words: [
    "full|滿的|adj.|The box is full.|盒子滿了。",
    "empty|空的|adj.|An empty bottle.|一個空樽。",
    "right|正確的|adj.|The right answer.|正確的答案。",
    "wrong|錯誤的|adj.|The wrong way.|錯誤的路。",
    "early|早的|adj.|An early bus.|早班巴士。",
    "late|遲的|adj.|A late train.|遲來的火車。",
    "near|近的|adj.|A near shop.|近的商店。",
    "far|遠的|adj.|A far place.|遠的地方。",
    "same|相同的|adj.|The same size.|相同尺碼。",
    "different|不同的|adj.|Different colours.|不同的顏色。"
  ]},
  { title: "核心高頻字 12（常用形容詞）", words: [
    "beautiful|美麗的|adj.|A beautiful flower.|一朵美麗的花。",
    "ugly|醜陋的|adj.|An ugly monster.|醜陋的怪物。",
    "rich|富有的|adj.|A rich man.|一個富人。",
    "poor|貧窮的|adj.|A poor family.|貧窮的家庭。",
    "strong|強壯的|adj.|A strong boy.|強壯的男孩。",
    "weak|虛弱的|adj.|A weak signal.|微弱的訊號。",
    "heavy|重的|adj.|A heavy bag.|重的袋子。",
    "light|輕的|adj.|A light box.|輕的箱子。",
    "wide|寬闊的|adj.|A wide road.|寬闊的路。",
    "narrow|狹窄的|adj.|A narrow street.|狹窄的街道。"
  ]},
  { title: "核心高頻字 13（常用形容詞）", words: [
    "busy|忙碌的|adj.|I am busy.|我很忙。",
    "free|空閒的；免費的|adj.|Are you free?|你有空嗎？",
    "ready|準備好的|adj.|I am ready.|我準備好了。",
    "tired|疲倦的|adj.|I am tired.|我很累。",
    "sick|生病的|adj.|He is sick.|他生病了。",
    "healthy|健康的|adj.|Healthy food.|健康的食物。",
    "hungry|肚餓的|adj.|I am hungry.|我很餓。",
    "thirsty|口渴的|adj.|I am thirsty.|我很渴。",
    "afraid|害怕的|adj.|I am afraid.|我害怕。",
    "angry|生氣的|adj.|He is angry.|他很生氣。"
  ]},
  { title: "核心高頻字 14（常用副詞）", words: [
    "always|總是|adv.|I always try.|我總是嘗試。",
    "usually|通常|adv.|I usually walk.|我通常走路。",
    "often|常常|adv.|I often read.|我常常閱讀。",
    "sometimes|有時|adv.|Sometimes I run.|我有時跑步。",
    "never|從不|adv.|I never lie.|我從不說謊。",
    "now|現在|adv.|Do it now.|現在就做。",
    "then|然後|adv.|Eat, then go.|先吃，然後走。",
    "here|這裡|adv.|Come here.|來這裡。",
    "there|那裡|adv.|Go there.|去那裡。",
    "very|非常|adv.|Very good.|非常好。"
  ]},
  { title: "核心高頻字 15（連接詞）", words: [
    "because|因為|conj.|Because it is cold.|因為天氣冷。",
    "but|但是|conj.|Small but strong.|小但強壯。",
    "and|和|conj.|You and me.|你和我。",
    "or|或者|conj.|Tea or coffee?|茶還是咖啡？",
    "so|所以|conj.|I am tired, so I rest.|我累，所以休息。",
    "if|如果|conj.|If it rains, stay.|如果下雨，就留在家。",
    "when|當…時|conj.|When I eat...|當我吃東西時…",
    "while|當…期間|conj.|While I work...|當我工作期間…",
    "before|在…之前|conj.|Before school...|上學前…",
    "after|在…之後|conj.|After lunch...|午餐後…"
  ]},
  { title: "核心高頻字 16（時間）", words: [
    "time|時間|n.|What time is it?|現在幾點？",
    "day|日子|n.|A good day.|美好的一天。",
    "week|星期|n.|Next week.|下星期。",
    "month|月份|n.|Last month.|上個月。",
    "year|年|n.|This year.|今年。",
    "today|今天|n.|Today is Monday.|今天是星期一。",
    "tomorrow|明天|n.|See you tomorrow.|明天見。",
    "yesterday|昨天|n.|I was busy yesterday.|我昨天很忙。",
    "morning|早上|n.|Good morning.|早安。",
    "night|晚上|n.|Good night.|晚安。"
  ]},
  { title: "核心高頻字 17（人物）", words: [
    "man|男人|n.|A tall man.|一個高男人。",
    "woman|女人|n.|A kind woman.|一個善良的女人。",
    "boy|男孩|n.|A little boy.|一個小男孩。",
    "girl|女孩|n.|A clever girl.|一個聰明的女孩。",
    "child|孩子|n.|One child.|一個孩子。",
    "children|孩子們|n.|Many children.|很多孩子。",
    "people|人們|n.|Many people.|很多人。",
    "family|家庭|n.|My family.|我的家庭。",
    "friend|朋友|n.|My best friend.|我最好的朋友。",
    "teacher|老師|n.|My teacher.|我的老師。"
  ]},
  { title: "核心高頻字 18（家庭成員）", words: [
    "mother|母親|n.|My mother.|我的母親。",
    "father|父親|n.|My father.|我的父親。",
    "parents|父母|n.|My parents.|我的父母。",
    "brother|兄弟|n.|My brother.|我的兄弟。",
    "sister|姊妹|n.|My sister.|我的姊妹。",
    "son|兒子|n.|Her son.|她的兒子。",
    "daughter|女兒|n.|His daughter.|他的女兒。",
    "baby|嬰兒|n.|A cute baby.|可愛的嬰兒。",
    "husband|丈夫|n.|Her husband.|她的丈夫。",
    "wife|妻子|n.|His wife.|他的妻子。"
  ]},
  { title: "核心高頻字 19（家居物品）", words: [
    "house|房屋|n.|My house.|我的房子。",
    "home|家|n.|Go home.|回家。",
    "room|房間|n.|My room.|我的房間。",
    "door|門|n.|Open the door.|開門。",
    "window|窗|n.|Close the window.|關窗。",
    "table|桌子|n.|On the table.|在桌上。",
    "chair|椅子|n.|Sit on the chair.|坐在椅上。",
    "bed|床|n.|Go to bed.|上床睡覺。",
    "phone|電話|n.|My phone.|我的電話。",
    "computer|電腦|n.|A computer.|一部電腦。"
  ]},
  { title: "核心高頻字 20（日常生活）", words: [
    "water|水|n.|Drink water.|喝水。",
    "food|食物|n.|Good food.|好食物。",
    "money|金錢|n.|Save money.|儲錢。",
    "book|書|n.|Read a book.|看書。",
    "car|汽車|n.|A red car.|紅色汽車。",
    "bus|巴士|n.|Take the bus.|乘巴士。",
    "school|學校|n.|Go to school.|上學。",
    "shop|商店|n.|A small shop.|小商店。",
    "street|街道|n.|On the street.|在街上。",
    "city|城市|n.|A big city.|大城市。"
  ]},
  { title: "核心高頻字 21（身體）", words: [
    "head|頭|n.|My head.|我的頭。",
    "face|臉|n.|Wash your face.|洗臉。",
    "hand|手|n.|My hand.|我的手。",
    "foot|腳|n.|My foot.|我的腳。",
    "eye|眼睛|n.|My eyes.|我的眼睛。",
    "ear|耳朵|n.|My ears.|我的耳朵。",
    "mouth|嘴巴|n.|Open your mouth.|張開嘴巴。",
    "hair|頭髮|n.|Long hair.|長頭髮。",
    "body|身體|n.|My body.|我的身體。",
    "heart|心臟|n.|My heart.|我的心臟。"
  ]},
  { title: "核心高頻字 22（自然天氣）", words: [
    "sun|太陽|n.|The sun is hot.|太陽很熱。",
    "moon|月亮|n.|The moon is bright.|月亮很亮。",
    "star|星星|n.|Many stars.|很多星星。",
    "sky|天空|n.|Blue sky.|藍天。",
    "rain|雨|n.|Heavy rain.|大雨。",
    "wind|風|n.|Strong wind.|強風。",
    "cloud|雲|n.|White clouds.|白雲。",
    "snow|雪|n.|White snow.|白雪。",
    "sea|海|n.|The blue sea.|藍色的海。",
    "tree|樹|n.|A tall tree.|高樹。"
  ]},
  { title: "核心高頻字 23（動物與顏色）", words: [
    "dog|狗|n.|A cute dog.|可愛的狗。",
    "cat|貓|n.|A small cat.|小貓。",
    "bird|鳥|n.|A bird sings.|鳥兒唱歌。",
    "fish|魚|n.|A fish swims.|魚游水。",
    "horse|馬|n.|A fast horse.|快馬。",
    "animal|動物|n.|A wild animal.|野生動物。",
    "red|紅色|adj.|A red apple.|紅蘋果。",
    "blue|藍色|adj.|A blue sea.|藍色的海。",
    "green|綠色|adj.|Green leaves.|綠葉。",
    "white|白色|adj.|White snow.|白雪。"
  ]},
  { title: "核心高頻字 24（數量）", words: [
    "one|一|num.|One apple.|一個蘋果。",
    "two|二|num.|Two hands.|兩隻手。",
    "three|三|num.|Three books.|三本書。",
    "ten|十|num.|Ten fingers.|十隻手指。",
    "hundred|一百|num.|One hundred.|一百。",
    "many|很多|det.|Many people.|很多人。",
    "much|很多（不可數）|det.|Too much water.|太多水。",
    "some|一些|det.|Some rice.|一些米。",
    "any|任何|det.|Any questions?|有任何問題嗎？",
    "all|全部|det.|All of us.|我們全部。"
  ]},
  { title: "核心高頻字 25（疑問詞與指示詞）", words: [
    "who|誰|pron.|Who is he?|他是誰？",
    "what|甚麼|pron.|What is this?|這是甚麼？",
    "where|哪裡|adv.|Where do you live?|你住在哪裡？",
    "when|何時|adv.|When do you come?|你何時來？",
    "why|為甚麼|adv.|Why are you late?|你為甚麼遲到？",
    "how|如何|adv.|How are you?|你好嗎？",
    "this|這個|pron.|This is my book.|這是我的書。",
    "that|那個|pron.|That is yours.|那是你的。",
    "these|這些|pron.|These are new.|這些是新的。",
    "those|那些|pron.|Those are old.|那些是舊的。"
  ]},
  { title: "核心高頻字 26（方位介系詞）", words: [
    "in|在…裡面|prep.|In the box.|在盒子裡。",
    "on|在…上面|prep.|On the table.|在桌上。",
    "at|在（地點／時間）|prep.|At school.|在學校。",
    "under|在…下面|prep.|Under the bed.|在床下。",
    "behind|在…後面|prep.|Behind the door.|在門後。",
    "between|在…之間|prep.|Between us.|在我們之間。",
    "above|在…上方|prep.|Above the desk.|在書桌上方。",
    "below|在…下方|prep.|Below zero.|零度以下。",
    "inside|在…裡面|prep.|Inside the room.|在房間裡面。",
    "outside|在…外面|prep.|Outside the house.|在屋外。"
  ]},
  { title: "核心高頻字 27（常用形容詞 2）", words: [
    "first|第一|adj.|The first day.|第一天。",
    "last|最後|adj.|The last question.|最後一題。",
    "next|下一個|adj.|Next week.|下星期。",
    "every|每一個|det.|Every day.|每一天。",
    "each|每個|det.|Each student.|每個學生。",
    "other|其他的|adj.|Other people.|其他人。",
    "another|另一個|det.|Another one.|另一個。",
    "only|唯一|adj.|The only one.|唯一的一個。",
    "important|重要的|adj.|An important test.|重要的測驗。",
    "famous|著名的|adj.|A famous singer.|著名歌手。"
  ]},
  { title: "核心高頻字 28（常用動詞 2）", words: [
    "visit|探望；參觀|v.|Visit my friend.|探望朋友。",
    "travel|旅遊|v.|Travel to Japan.|去日本旅遊。",
    "arrive|到達|v.|I arrive early.|我早到。",
    "wait|等待|v.|Wait here.|在這裡等。",
    "hope|希望|v.|I hope so.|我希望如此。",
    "wish|祝願|v.|I wish you luck.|祝你好運。",
    "believe|相信|v.|I believe you.|我相信你。",
    "agree|同意|v.|I agree.|我同意。",
    "decide|決定|v.|I decide to go.|我決定去。",
    "miss|想念|v.|I miss you.|我想念你。"
  ]},
  { title: "核心高頻字 29（常用名詞）", words: [
    "idea|主意|n.|A good idea.|好主意。",
    "question|問題|n.|A hard question.|難題。",
    "answer|答案|n.|The right answer.|正確答案。",
    "problem|難題|n.|A big problem.|大問題。",
    "story|故事|n.|A short story.|短故事。",
    "word|字|n.|A new word.|新字。",
    "name|名字|n.|My name.|我的名字。",
    "number|數字|n.|Your number.|你的號碼。",
    "colour|顏色|n.|What colour?|甚麼顏色？",
    "game|遊戲|n.|Play a game.|玩遊戲。"
  ]},
  { title: "核心高頻字 30（程度副詞）", words: [
    "too|太；也|adv.|Too hot.|太熱。",
    "also|也|adv.|I also like it.|我也喜歡。",
    "again|再次|adv.|Try again.|再試一次。",
    "still|仍然|adv.|I am still here.|我仍在這裡。",
    "really|真的|adv.|Really good.|真的很好。",
    "quite|頗為|adv.|Quite easy.|頗容易。",
    "almost|幾乎|adv.|Almost done.|快完成了。",
    "together|一起|adv.|We go together.|我們一起去。",
    "away|離開|adv.|Go away.|走開。",
    "back|回來|adv.|Come back.|回來。"
  ]},
  { title: "考試指令詞（Exam Instruction Words）", words: [
    "complete|完成|v.|Complete the sentence.|完成句子。",
    "choose|選擇|v.|Choose the answer.|選擇答案。",
    "match|配對|v.|Match the words.|配對詞語。",
    "describe|描述|v.|Describe the picture.|描述圖片。",
    "explain|解釋|v.|Explain your answer.|解釋你的答案。",
    "list|列出|v.|List three things.|列出三樣東西。",
    "compare|比較|v.|Compare the two.|比較兩者。",
    "correct|改正|v.|Correct the mistakes.|改正錯誤。",
    "fill|填寫|v.|Fill in the blank.|填充。",
    "underline|在下面畫線|v.|Underline the verb.|在動詞下畫線。",
    "circle|圈起來|v.|Circle the answer.|圈出答案。",
    "tick|打勾|v.|Tick the box.|在方格打勾。",
    "arrange|排列|v.|Arrange in order.|按次序排列。",
    "suggest|建議|v.|Suggest a title.|建議一個標題。",
    "identify|指出|v.|Identify the speaker.|指出說話者。",
    "mention|提及|v.|Mention two points.|提及兩點。",
    "replace|代替|v.|Replace the word.|代替那個字。",
    "provide|提供|v.|Provide an example.|提供一個例子。"
  ]},
  { title: "主題詞彙 · 學校與學習", words: [
    "classroom|課室|n.|My classroom.|我的課室。",
    "library|圖書館|n.|Go to the library.|去圖書館。",
    "pencil|鉛筆|n.|A pencil.|一支鉛筆。",
    "pen|原子筆|n.|A blue pen.|一支藍筆。",
    "paper|紙|n.|A piece of paper.|一張紙。",
    "homework|功課|n.|Do your homework.|做功課。",
    "exam|考試|n.|A big exam.|大考。",
    "test|測驗|n.|A maths test.|數學測驗。",
    "lesson|課堂|n.|An English lesson.|英文課。",
    "subject|科目|n.|My favourite subject.|我最喜歡的科目。",
    "English|英文|n.|I study English.|我讀英文。",
    "Chinese|中文|n.|Chinese is useful.|中文很有用。",
    "maths|數學|n.|Maths is hard.|數學很難。",
    "science|科學|n.|I like science.|我喜歡科學。",
    "history|歷史|n.|History is fun.|歷史很有趣。",
    "geography|地理|n.|Geography lesson.|地理課。",
    "music|音樂|n.|I love music.|我愛音樂。",
    "art|美術|n.|An art class.|美術課。",
    "classmate|同學|n.|My classmate.|我的同學。",
    "student|學生|n.|A hard-working student.|勤奮的學生。"
  ]},
  { title: "主題詞彙 · 家庭與人物", words: [
    "grandmother|祖母|n.|My grandmother.|我的祖母。",
    "grandfather|祖父|n.|My grandfather.|我的祖父。",
    "uncle|叔叔|n.|My uncle.|我的叔叔。",
    "aunt|姨母|n.|My aunt.|我的姨母。",
    "cousin|表／堂兄弟姊妹|n.|My cousin.|我的表兄弟。",
    "neighbour|鄰居|n.|A kind neighbour.|好鄰居。",
    "parent|家長|n.|A parent.|一位家長。",
    "boyfriend|男朋友|n.|Her boyfriend.|她的男朋友。",
    "girlfriend|女朋友|n.|His girlfriend.|他的女朋友。",
    "boss|老闆|n.|My boss.|我的老闆。",
    "worker|工人|n.|A worker.|一個工人。",
    "doctor|醫生|n.|See a doctor.|看醫生。",
    "nurse|護士|n.|A nurse.|一位護士。",
    "driver|司機|n.|A bus driver.|巴士司機。",
    "cook|廚師|n.|A good cook.|好廚師。",
    "policeman|警察|n.|A policeman.|一位警察。",
    "waiter|侍應|n.|A waiter.|侍應。",
    "baby|嬰兒|n.|A baby.|嬰兒。",
    "adult|成人|n.|An adult.|成人。",
    "person|人|n.|A kind person.|善良的人。"
  ]},
  { title: "主題詞彙 · 食物與飲品", words: [
    "breakfast|早餐|n.|Eat breakfast.|吃早餐。",
    "lunch|午餐|n.|Have lunch.|吃午餐。",
    "dinner|晚餐|n.|Cook dinner.|煮晚餐。",
    "rice|米飯|n.|A bowl of rice.|一碗飯。",
    "noodles|麵條|n.|A bowl of noodles.|一碗麵。",
    "bread|麵包|n.|Some bread.|一些麵包。",
    "egg|雞蛋|n.|Two eggs.|兩隻蛋。",
    "meat|肉|n.|Some meat.|一些肉。",
    "vegetable|蔬菜|n.|Eat vegetables.|吃蔬菜。",
    "fruit|水果|n.|Fresh fruit.|新鮮水果。",
    "apple|蘋果|n.|An apple.|一個蘋果。",
    "banana|香蕉|n.|A banana.|一條香蕉。",
    "milk|牛奶|n.|A glass of milk.|一杯牛奶。",
    "tea|茶|n.|A cup of tea.|一杯茶。",
    "coffee|咖啡|n.|A cup of coffee.|一杯咖啡。",
    "juice|果汁|n.|Orange juice.|橙汁。",
    "soup|湯|n.|Hot soup.|熱湯。",
    "cake|蛋糕|n.|A birthday cake.|生日蛋糕。",
    "chicken|雞|n.|Fried chicken.|炸雞。",
    "snack|小食|n.|A small snack.|小食。"
  ]},
  { title: "主題詞彙 · 購物與金錢", words: [
    "market|市場|n.|A wet market.|街市。",
    "supermarket|超級市場|n.|A supermarket.|超級市場。",
    "price|價錢|n.|A low price.|低價。",
    "cheap|便宜的|adj.|Cheap food.|便宜的食物。",
    "expensive|昂貴的|adj.|An expensive car.|昂貴的車。",
    "cash|現金|n.|Pay in cash.|用現金付款。",
    "change|找續|n.|Keep the change.|不用找續。",
    "customer|顧客|n.|A customer.|顧客。",
    "clothes|衣服|n.|New clothes.|新衣服。",
    "shoes|鞋子|n.|A pair of shoes.|一對鞋。",
    "bag|袋子|n.|A shopping bag.|購物袋。",
    "wallet|錢包|n.|My wallet.|我的錢包。",
    "discount|折扣|n.|A big discount.|大折扣。",
    "receipt|收據|n.|Keep the receipt.|保留收據。",
    "size|尺碼|n.|What size?|甚麼尺碼？",
    "brand|品牌|n.|A famous brand.|著名品牌。",
    "gift|禮物|n.|A birthday gift.|生日禮物。",
    "queue|排隊|n.|Stand in a queue.|排隊。",
    "sale|減價|n.|A big sale.|大減價。",
    "pay|付款|v.|Pay the bill.|付帳單。"
  ]},
  { title: "主題詞彙 · 天氣與季節", words: [
    "weather|天氣|n.|Good weather.|好天氣。",
    "sunny|晴朗的|adj.|A sunny day.|晴天。",
    "rainy|下雨的|adj.|A rainy day.|雨天。",
    "cloudy|多雲的|adj.|A cloudy sky.|多雲的天空。",
    "windy|有風的|adj.|A windy day.|大風天。",
    "warm|溫暖的|adj.|Warm weather.|溫暖的天氣。",
    "cool|涼快的|adj.|A cool day.|涼快的一天。",
    "storm|暴風雨|n.|A big storm.|大風暴。",
    "typhoon|颱風|n.|A typhoon.|颱風。",
    "spring|春天|n.|In spring.|在春天。",
    "summer|夏天|n.|In summer.|在夏天。",
    "autumn|秋天|n.|In autumn.|在秋天。",
    "winter|冬天|n.|In winter.|在冬天。",
    "temperature|溫度|n.|High temperature.|高溫。",
    "forecast|預報|n.|The weather forecast.|天氣預報。",
    "dry|乾燥的|adj.|Dry weather.|乾燥天氣。",
    "wet|潮濕的|adj.|A wet day.|潮濕的一天。",
    "bright|光亮的|adj.|Bright sunshine.|明亮的陽光。",
    "foggy|有霧的|adj.|A foggy morning.|有霧的早晨。",
    "freeze|結冰|v.|Water freezes.|水結冰。"
  ]},
  { title: "主題詞彙 · 健康與身體", words: [
    "health|健康|n.|Good health.|身體健康。",
    "nose|鼻子|n.|My nose.|我的鼻子。",
    "ill|生病的|adj.|He is ill.|他病了。",
    "headache|頭痛|n.|I have a headache.|我頭痛。",
    "medicine|藥物|n.|Take medicine.|吃藥。",
    "hospital|醫院|n.|Go to hospital.|去醫院。",
    "exercise|運動|n.|Do exercise.|做運動。",
    "rest|休息|n.|Take a rest.|休息。",
    "pain|痛|n.|I feel pain.|我感到痛。",
    "hurt|弄傷|v.|My leg hurts.|我的腿痛。",
    "fever|發燒|n.|I have a fever.|我發燒。",
    "cold|感冒|n.|I have a cold.|我感冒。",
    "cough|咳嗽|v.|I cough a lot.|我常咳嗽。",
    "tooth|牙齒|n.|Brush your teeth.|刷牙。",
    "stomach|肚子|n.|My stomach hurts.|我肚子痛。",
    "finger|手指|n.|My finger.|我的手指。",
    "leg|腿|n.|My leg.|我的腿。",
    "arm|手臂|n.|My arm.|我的手臂。",
    "doctor|醫生|n.|A doctor.|醫生。",
    "healthy|健康的|adj.|Stay healthy.|保持健康。"
  ]},
  { title: "主題詞彙 · 興趣與休閒", words: [
    "hobby|嗜好|n.|My hobby.|我的嗜好。",
    "sport|運動|n.|I like sport.|我喜歡運動。",
    "football|足球|n.|Play football.|踢足球。",
    "basketball|籃球|n.|Play basketball.|打籃球。",
    "swimming|游泳|n.|Go swimming.|去游泳。",
    "running|跑步|n.|Go running.|去跑步。",
    "song|歌曲|n.|Sing a song.|唱歌。",
    "dance|跳舞|v.|I love to dance.|我喜歡跳舞。",
    "sing|唱歌|v.|I can sing.|我會唱歌。",
    "draw|畫畫|v.|I draw pictures.|我畫圖畫。",
    "painting|繪畫|n.|A painting.|一幅畫。",
    "reading|閱讀|n.|I like reading.|我喜歡閱讀。",
    "movie|電影|n.|Watch a movie.|看電影。",
    "film|電影|n.|A good film.|好電影。",
    "camping|露營|n.|Go camping.|去露營。",
    "picnic|野餐|n.|Have a picnic.|去野餐。",
    "photo|照片|n.|Take a photo.|拍照。",
    "party|派對|n.|A birthday party.|生日派對。",
    "fun|樂趣|n.|Have fun.|玩得開心。",
    "relax|放鬆|v.|Relax at home.|在家放鬆。"
  ]},
  { title: "主題詞彙 · 地點與交通", words: [
    "place|地方|n.|A nice place.|好地方。",
    "town|市鎮|n.|My town.|我的市鎮。",
    "village|鄉村|n.|A small village.|小鄉村。",
    "country|國家|n.|My country.|我的國家。",
    "park|公園|n.|Go to the park.|去公園。",
    "beach|海灘|n.|At the beach.|在海灘。",
    "restaurant|餐廳|n.|A restaurant.|餐廳。",
    "hotel|酒店|n.|Stay in a hotel.|住酒店。",
    "bank|銀行|n.|Go to the bank.|去銀行。",
    "station|車站|n.|A train station.|火車站。",
    "airport|機場|n.|At the airport.|在機場。",
    "train|火車|n.|Take the train.|乘火車。",
    "taxi|的士|n.|Take a taxi.|乘的士。",
    "bicycle|單車|n.|Ride a bicycle.|踏單車。",
    "road|道路|n.|Cross the road.|過馬路。",
    "map|地圖|n.|Read a map.|看地圖。",
    "ticket|車票|n.|Buy a ticket.|買車票。",
    "bus|巴士|n.|A bus.|巴士。",
    "museum|博物館|n.|Visit a museum.|參觀博物館。",
    "cinema|戲院|n.|Go to the cinema.|去戲院。"
  ]}
];
